name: dhurandhar
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.2
  firebase_messaging: ^14.2.2
  firebase_crashlytics: ^3.1.2
  logger: ^2.1.0
  fluttertoast: ^8.2.4
  google_fonts: ^4.0.1
  # sqflite: ^2.3.2
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.10+1
  connectivity_plus: ^5.0.2
  provider: ^6.1.2
  get_it: ^7.6.7
  image_picker: ^1.0.7
  iconsax: ^0.0.8
  carousel_slider: ^4.2.1
  location_picker_flutter_map: ^3.0.1
  intl: ^0.19.0
  geolocator: ^10.1.1
  geocoding: ^3.0.0
  permission_handler: ^11.3.0
  firebase_database: ^10.4.9
  rxdart: ^0.27.7
  shimmer: ^3.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/onboardingTour/
    - assets/banners/
    - assets/animations/


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
